"""add reportsource table

Revision ID: a3f48b3b2b6b
Revises: 40af779631bb
Create Date: 2019-11-21 23:29:02.941358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f48b3b2b6b'
down_revision = '40af779631bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportsource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source', sa.String(length=128), nullable=True),
    sa.Column('kode_pos', sa.String(length=128), nullable=True),
    sa.Column('desa', sa.String(length=128), nullable=True),
    sa.Column('kode', sa.String(length=128), nullable=True),
    sa.Column('kecamatan', sa.String(length=128), nullable=True),
    sa.Column('dt2', sa.String(length=128), nullable=True),
    sa.Column('kota', sa.String(length=128), nullable=True),
    sa.Column('provinsi', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('datasources', 'site_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('datasources', 'site_url',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasources', 'site_url',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('datasources', 'site_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_table('reportsource')
    # ### end Alembic commands ###
